version: "3"

services:
  mi2:
    build:
      context: "."
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    network_mode: "host"
    restart: always
  db:
    image: postgres:13.7
    restart: always
    command: postgres -c password_encryption=md5
    platform: linux/arm64/v8
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5438:5432'
    volumes: 
      - ./pg:/var/lib/postgresql/data
